// Generated from apps/api/src (app-lite.ts + app-ai.ts mounts) on 2026-10-02.
// Every endpoint here accepts an Avise API key. Regenerate when routes change.

export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export interface EndpointIndexGroup {
  title: string;
  note?: string;
  endpoints: [HttpMethod, string][];
}

export const ENDPOINT_TOTAL = 315;

export const ENDPOINT_INDEX: EndpointIndexGroup[] = [
  {
    title: "Deals",
    endpoints: [
      ["GET", "/api/deals"],
      ["POST", "/api/deals"],
      ["GET", "/api/deals/:dealId/access-timeline"],
      ["GET", "/api/deals/:dealId/activities"],
      ["POST", "/api/deals/:dealId/activities"],
      ["GET", "/api/deals/:dealId/ai-cache"],
      ["DELETE", "/api/deals/:dealId/ai-cache"],
      ["POST", "/api/deals/:dealId/analyze-risks"],
      ["POST", "/api/deals/:dealId/chat"],
      ["GET", "/api/deals/:dealId/chat/history"],
      ["DELETE", "/api/deals/:dealId/chat/history"],
      ["GET", "/api/deals/:dealId/doc-requests"],
      ["POST", "/api/deals/:dealId/doc-requests"],
      ["PATCH", "/api/deals/:dealId/doc-requests/:id"],
      ["DELETE", "/api/deals/:dealId/doc-requests/:id"],
      ["POST", "/api/deals/:dealId/doc-requests/:id/remind"],
      ["GET", "/api/deals/:dealId/doc-requests/templates"],
      ["POST", "/api/deals/:dealId/document-requests"],
      ["GET", "/api/deals/:dealId/documents"],
      ["POST", "/api/deals/:dealId/documents"],
      ["POST", "/api/deals/:dealId/documents/from-drive"],
      ["GET", "/api/deals/:dealId/financials"],
      ["PATCH", "/api/deals/:dealId/financials/:statementId"],
      ["GET", "/api/deals/:dealId/financials/analysis"],
      ["GET", "/api/deals/:dealId/financials/benchmark"],
      ["DELETE", "/api/deals/:dealId/financials/by-document/:documentId"],
      ["GET", "/api/deals/:dealId/financials/conflicts"],
      ["GET", "/api/deals/:dealId/financials/cross-doc"],
      ["POST", "/api/deals/:dealId/financials/extract"],
      ["GET", "/api/deals/:dealId/financials/insights"],
      ["POST", "/api/deals/:dealId/financials/insights/regenerate"],
      ["GET", "/api/deals/:dealId/financials/memo"],
      ["POST", "/api/deals/:dealId/financials/resolve"],
      ["POST", "/api/deals/:dealId/financials/resolve-all"],
      ["GET", "/api/deals/:dealId/financials/summary"],
      ["GET", "/api/deals/:dealId/financials/timeseries"],
      ["GET", "/api/deals/:dealId/financials/validation"],
      ["GET", "/api/deals/:dealId/folders"],
      ["POST", "/api/deals/:dealId/folders"],
      ["POST", "/api/deals/:dealId/folders/init"],
      ["POST", "/api/deals/:dealId/generate-thesis"],
      ["GET", "/api/deals/:dealId/graphs"],
      ["POST", "/api/deals/:dealId/graphs"],
      ["GET", "/api/deals/:dealId/legal-documents"],
      ["POST", "/api/deals/:dealId/legal-documents"],
      ["POST", "/api/deals/:dealId/legal-documents/import-gdoc"],
      ["POST", "/api/deals/:dealId/legal-documents/upload"],
      ["GET", "/api/deals/:dealId/model"],
      ["PUT", "/api/deals/:dealId/model"],
      ["GET", "/api/deals/:dealId/model/cases"],
      ["POST", "/api/deals/:dealId/model/export"],
      ["GET", "/api/deals/:dealId/nda-reviews"],
      ["POST", "/api/deals/:dealId/nda-reviews"],
      ["PATCH", "/api/deals/:dealId/reactivations/:id"],
      ["POST", "/api/deals/:dealId/rescore"],
      ["POST", "/api/deals/:dealId/scorecard"],
      ["GET", "/api/deals/:dealId/shares"],
      ["POST", "/api/deals/:dealId/shares"],
      ["DELETE", "/api/deals/:dealId/shares/:shareId"],
      ["PATCH", "/api/deals/:dealId/team/:memberId"],
      ["DELETE", "/api/deals/:dealId/team/:memberId"],
      ["GET", "/api/deals/:id"],
      ["PATCH", "/api/deals/:id"],
      ["DELETE", "/api/deals/:id"],
      ["POST", "/api/deals/:id/analyze"],
      ["GET", "/api/deals/:id/extraction-debug"],
      ["POST", "/api/deals/:id/follow-up-questions"],
      ["GET", "/api/deals/:id/reconcile"],
      ["POST", "/api/deals/:id/restore"],
      ["GET", "/api/deals/:id/team"],
      ["POST", "/api/deals/:id/team"],
      ["GET", "/api/deals/:id/teasers"],
      ["POST", "/api/deals/:id/teasers"],
      ["GET", "/api/deals/financial-summaries"],
      ["POST", "/api/deals/import"],
      ["POST", "/api/deals/import/analyze"],
      ["GET", "/api/deals/reactivations"],
      ["GET", "/api/deals/stats/summary"],
      ["GET", "/api/deals/trash"],
    ],
  },
  {
    title: "Contacts",
    endpoints: [
      ["GET", "/api/contacts"],
      ["POST", "/api/contacts"],
      ["DELETE", "/api/contacts/:contactId/deals/:dealId"],
      ["GET", "/api/contacts/:id"],
      ["PATCH", "/api/contacts/:id"],
      ["DELETE", "/api/contacts/:id"],
      ["GET", "/api/contacts/:id/connections"],
      ["POST", "/api/contacts/:id/connections"],
      ["DELETE", "/api/contacts/:id/connections/:connectionId"],
      ["POST", "/api/contacts/:id/deals"],
      ["GET", "/api/contacts/:id/email-summary"],
      ["POST", "/api/contacts/:id/interactions"],
      ["GET", "/api/contacts/export"],
      ["POST", "/api/contacts/import"],
      ["GET", "/api/contacts/insights/duplicates"],
      ["GET", "/api/contacts/insights/follow-ups"],
      ["GET", "/api/contacts/insights/gmail-suggestions"],
      ["GET", "/api/contacts/insights/network"],
      ["GET", "/api/contacts/insights/scores"],
      ["GET", "/api/contacts/insights/stale"],
      ["GET", "/api/contacts/insights/timeline"],
    ],
  },
  {
    title: "Companies",
    endpoints: [
      ["GET", "/api/companies"],
      ["POST", "/api/companies"],
      ["GET", "/api/companies/:id"],
      ["PATCH", "/api/companies/:id"],
      ["DELETE", "/api/companies/:id"],
    ],
  },
  {
    title: "Tasks",
    endpoints: [
      ["GET", "/api/tasks"],
      ["POST", "/api/tasks"],
      ["GET", "/api/tasks/:id"],
      ["PATCH", "/api/tasks/:id"],
      ["DELETE", "/api/tasks/:id"],
    ],
  },
  {
    title: "Activities and notes",
    endpoints: [
      ["GET", "/api/activities/:id"],
      ["DELETE", "/api/activities/:id"],
      ["GET", "/api/activities/recent"],
    ],
  },
  {
    title: "Documents, folders and data rooms",
    endpoints: [
      ["GET", "/api/data-rooms/summary"],
      ["POST", "/api/documents/:documentId/extract-financials"],
      ["GET", "/api/documents/:id"],
      ["PATCH", "/api/documents/:id"],
      ["DELETE", "/api/documents/:id"],
      ["POST", "/api/documents/:id/analyze"],
      ["GET", "/api/documents/:id/download"],
      ["POST", "/api/documents/:id/link"],
      ["GET", "/api/documents/alerts"],
      ["GET", "/api/folders/:folderId/documents"],
      ["GET", "/api/folders/:id"],
      ["PATCH", "/api/folders/:id"],
      ["DELETE", "/api/folders/:id"],
      ["POST", "/api/folders/:id/generate-insights"],
      ["GET", "/api/folders/:id/insights"],
      ["POST", "/api/folders/:id/insights"],
      ["POST", "/api/uploads/sign"],
    ],
  },
  {
    title: "Ingest (AI: create deals from files, text, URLs, email)",
    note: "Uses AI. 30 calls a minute.",
    endpoints: [
      ["POST", "/api/ingest"],
      ["GET", "/api/ingest/:dealId/extraction"],
      ["POST", "/api/ingest/:dealId/review"],
      ["POST", "/api/ingest/bulk"],
      ["POST", "/api/ingest/drive"],
      ["POST", "/api/ingest/email"],
      ["GET", "/api/ingest/pending-review"],
      ["POST", "/api/ingest/text"],
      ["POST", "/api/ingest/url"],
    ],
  },
  {
    title: "Investment memos (AI)",
    note: "Uses AI.",
    endpoints: [
      ["GET", "/api/memos"],
      ["POST", "/api/memos"],
      ["GET", "/api/memos/:id"],
      ["PATCH", "/api/memos/:id"],
      ["DELETE", "/api/memos/:id"],
      ["POST", "/api/memos/:id/chat"],
      ["GET", "/api/memos/:id/conversations"],
      ["POST", "/api/memos/:id/generate-all"],
      ["GET", "/api/memos/:id/sections"],
      ["POST", "/api/memos/:id/sections"],
      ["PATCH", "/api/memos/:id/sections/:sectionId"],
      ["DELETE", "/api/memos/:id/sections/:sectionId"],
      ["POST", "/api/memos/:id/sections/:sectionId/apply"],
      ["POST", "/api/memos/:id/sections/:sectionId/generate"],
      ["POST", "/api/memos/:id/sections/reorder"],
      ["GET", "/api/memos/debug"],
      ["POST", "/api/memos/suggest-meta"],
    ],
  },
  {
    title: "Legal documents and NDA review",
    note: "Some routes use AI.",
    endpoints: [
      ["GET", "/api/legal-document-templates"],
      ["POST", "/api/legal-document-templates"],
      ["PATCH", "/api/legal-document-templates/:id"],
      ["DELETE", "/api/legal-document-templates/:id"],
      ["POST", "/api/legal-document-templates/parse"],
      ["GET", "/api/legal-documents"],
      ["PATCH", "/api/legal-documents/:id"],
      ["DELETE", "/api/legal-documents/:id"],
      ["GET", "/api/legal-documents/:id/export"],
      ["POST", "/api/legal-documents/:id/request-signature"],
      ["POST", "/api/legal-documents/:id/send"],
      ["POST", "/api/legal-documents/:id/send-for-signature"],
      ["POST", "/api/legal-documents/check-signatures"],
      ["GET", "/api/nda-reviews/:id"],
    ],
  },
  {
    title: "AI assistant and chat",
    note: "Uses AI. 10 calls a minute on /api/ai.",
    endpoints: [
      ["POST", "/api/ai/chat"],
      ["POST", "/api/ai/chat/stream"],
      ["POST", "/api/ai/draft-email"],
      ["GET", "/api/ai/email-templates"],
      ["POST", "/api/ai/enrich-contact"],
      ["POST", "/api/ai/extract"],
      ["POST", "/api/ai/ingest"],
      ["GET", "/api/ai/market-sentiment"],
      ["POST", "/api/ai/meeting-prep"],
      ["POST", "/api/ai/scan-inbox"],
      ["POST", "/api/ai/scan-inbox/stream"],
      ["POST", "/api/ai/scan-signals"],
      ["GET", "/api/ai/status"],
      ["POST", "/api/ai/suggest-follow-up"],
      ["GET", "/api/conversations"],
      ["POST", "/api/conversations"],
      ["GET", "/api/conversations/:id"],
      ["DELETE", "/api/conversations/:id"],
      ["GET", "/api/conversations/:id/messages"],
      ["POST", "/api/conversations/:id/messages"],
      ["POST", "/api/portfolio/chat"],
    ],
  },
  {
    title: "Notifications",
    endpoints: [
      ["GET", "/api/notifications"],
      ["POST", "/api/notifications"],
      ["DELETE", "/api/notifications"],
      ["GET", "/api/notifications/:id"],
      ["PATCH", "/api/notifications/:id"],
      ["DELETE", "/api/notifications/:id"],
      ["POST", "/api/notifications/generate-follow-up-reminders"],
      ["POST", "/api/notifications/mark-all-read"],
    ],
  },
  {
    title: "Users and team",
    endpoints: [
      ["GET", "/api/invitations"],
      ["POST", "/api/invitations"],
      ["DELETE", "/api/invitations/:id"],
      ["POST", "/api/invitations/:id/resend"],
      ["POST", "/api/invitations/accept/:token"],
      ["POST", "/api/invitations/bulk"],
      ["POST", "/api/invitations/join/:token"],
      ["GET", "/api/invitations/verify/:token"],
      ["GET", "/api/users"],
      ["POST", "/api/users"],
      ["GET", "/api/users/:id"],
      ["PATCH", "/api/users/:id"],
      ["DELETE", "/api/users/:id"],
      ["GET", "/api/users/:id/deals"],
      ["GET", "/api/users/:id/notifications"],
      ["GET", "/api/users/me"],
      ["PATCH", "/api/users/me"],
      ["POST", "/api/users/me/avatar"],
      ["GET", "/api/users/me/team"],
    ],
  },
  {
    title: "Organization and firm profile",
    endpoints: [
      ["GET", "/api/firm-context"],
      ["PUT", "/api/firm-context"],
      ["POST", "/api/firm-context/generate"],
      ["GET", "/api/firm-teaser"],
      ["PUT", "/api/firm-teaser"],
      ["POST", "/api/firm-teaser/extract-context"],
      ["POST", "/api/firm-teaser/generate-prompt"],
      ["POST", "/api/onboarding/complete-step"],
      ["POST", "/api/onboarding/create-demo-deal"],
      ["POST", "/api/onboarding/dismiss"],
      ["POST", "/api/onboarding/enrich-firm"],
      ["POST", "/api/onboarding/firm-inputs"],
      ["POST", "/api/onboarding/firm-profile"],
      ["GET", "/api/onboarding/research-status"],
      ["GET", "/api/onboarding/status"],
      ["POST", "/api/onboarding/welcome-shown"],
      ["GET", "/api/organizations/criteria"],
      ["PATCH", "/api/organizations/criteria"],
      ["GET", "/api/organizations/me"],
      ["PATCH", "/api/organizations/me"],
      ["PATCH", "/api/organizations/me/staff-access-webhook"],
      ["GET", "/api/organizations/nda-playbook"],
      ["PATCH", "/api/organizations/nda-playbook"],
    ],
  },
  {
    title: "Templates",
    endpoints: [
      ["GET", "/api/templates"],
      ["POST", "/api/templates"],
      ["GET", "/api/templates/:id"],
      ["PATCH", "/api/templates/:id"],
      ["DELETE", "/api/templates/:id"],
      ["POST", "/api/templates/:id/duplicate"],
      ["GET", "/api/templates/:id/sections"],
      ["POST", "/api/templates/:id/sections"],
      ["PATCH", "/api/templates/:id/sections/:sectionId"],
      ["DELETE", "/api/templates/:id/sections/:sectionId"],
      ["POST", "/api/templates/:id/sections/reorder"],
      ["POST", "/api/templates/:id/use"],
    ],
  },
  {
    title: "Watchlist",
    endpoints: [
      ["GET", "/api/watchlist"],
      ["POST", "/api/watchlist"],
      ["DELETE", "/api/watchlist/:id"],
    ],
  },
  {
    title: "Relationship graphs",
    endpoints: [
      ["GET", "/api/graphs"],
      ["PATCH", "/api/graphs/:graphId"],
      ["DELETE", "/api/graphs/:graphId"],
    ],
  },
  {
    title: "Integrations (Gmail, Calendar, Granola, HubSpot\u2026)",
    endpoints: [
      ["GET", "/api/integrations"],
      ["DELETE", "/api/integrations/:id"],
      ["GET", "/api/integrations/:id/events"],
      ["POST", "/api/integrations/:id/sync"],
      ["POST", "/api/integrations/:provider/api-key"],
      ["POST", "/api/integrations/:provider/connect"],
      ["GET", "/api/integrations/activities"],
      ["GET", "/api/integrations/hubspot/connect"],
      ["POST", "/api/integrations/hubspot/connect"],
      ["DELETE", "/api/integrations/hubspot/connect"],
      ["POST", "/api/integrations/hubspot/import"],
      ["GET", "/api/integrations/hubspot/import/:id"],
      ["POST", "/api/integrations/hubspot/import/:id/cancel"],
      ["POST", "/api/integrations/hubspot/import/:id/continue"],
    ],
  },
  {
    title: "Audit log and export",
    endpoints: [
      ["GET", "/api/audit"],
      ["GET", "/api/audit/entity/:entityId"],
      ["GET", "/api/audit/export.csv"],
      ["GET", "/api/audit/summary"],
      ["GET", "/api/export/deals"],
    ],
  },
  {
    title: "Usage",
    endpoints: [
      ["GET", "/api/usage/me"],
    ],
  },
  {
    title: "Account security and sessions",
    endpoints: [
      ["POST", "/api/account/security/login-check"],
      ["POST", "/api/account/security/password-changed"],
      ["GET", "/api/auth/sessions"],
      ["DELETE", "/api/auth/sessions/:id"],
      ["GET", "/api/auth/workspace-email"],
    ],
  },
  {
    title: "Webhooks (outbound events)",
    note: "Organization admins. API keys allowed, so tools can register their own trigger URLs.",
    endpoints: [
      ["GET", "/api/webhook-subscriptions"],
      ["POST", "/api/webhook-subscriptions"],
      ["PATCH", "/api/webhook-subscriptions/:id"],
      ["DELETE", "/api/webhook-subscriptions/:id"],
      ["POST", "/api/webhook-subscriptions/:id/test"],
      ["GET", "/api/webhook-subscriptions/events"],
    ],
  },
  {
    title: "API key management",
    note: "Signed-in admins only. Every call made with an API key returns 403.",
    endpoints: [
      ["GET", "/api/api-keys"],
      ["POST", "/api/api-keys"],
      ["DELETE", "/api/api-keys/:id"],
    ],
  },
  {
    title: "Admin security",
    note: "Org admins only.",
    endpoints: [
      ["GET", "/api/admin/security/dashboard"],
      ["POST", "/api/admin/security/run-isolation-test"],
    ],
  },
  {
    title: "Outreach",
    note: "Only enabled for one organization; others get 403.",
    endpoints: [
      ["GET", "/api/outreach/campaigns"],
      ["GET", "/api/outreach/contacts"],
      ["POST", "/api/outreach/contacts"],
      ["PATCH", "/api/outreach/contacts/:id"],
      ["DELETE", "/api/outreach/contacts/:id"],
      ["POST", "/api/outreach/contacts/:id/enrich"],
      ["POST", "/api/outreach/contacts/:id/send"],
      ["POST", "/api/outreach/import/clay-csv"],
      ["POST", "/api/outreach/import/private-circle"],
      ["GET", "/api/outreach/settings"],
      ["PATCH", "/api/outreach/settings"],
      ["POST", "/api/outreach/settings/reset"],
      ["GET", "/api/outreach/stages"],
      ["POST", "/api/outreach/sync-replies"],
    ],
  },
  {
    title: "Avise staff only",
    note: "Avise internal staff only; customers get 403.",
    endpoints: [
      ["GET", "/api/internal/usage/cost-breakdown"],
      ["GET", "/api/internal/usage/events"],
      ["GET", "/api/internal/usage/leaderboard"],
      ["GET", "/api/internal/usage/reconciliation"],
      ["POST", "/api/internal/users/:userId/block"],
      ["POST", "/api/internal/users/:userId/throttle"],
    ],
  },
];
